brew_logs/urls.py
from django.urls import path

from brew_logs.views import (
    BrewLogCreateView,
    BrewLogDeleteView,
    BrewLogDetailView,
    BrewLogListView,
    BrewLogUpdateView,
)


urlpatterns = [
    path("", BrewLogListView.as_view(), name="list_brewlogs"),
    path("<int:pk>/", BrewLogDetailView.as_view(), name="show_brewlog"),
    path("create/", BrewLogCreateView.as_view(), name="create_brewlog"),
    path("<int:pk>/delete/", BrewLogDeleteView.as_view(), name="delete_brewlog"),
    path("<int:pk>/edit/", BrewLogUpdateView.as_view(), name="edit_brewlog"),
]

brewr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("accounts/", include("accounts.urls")),
    path("tags/", include("tags.urls")),
    path("brew_logs", include("brew_logs.urls")),
    path("", RedirectView.as_view(url="/recipes/"), name="home"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagDeleteView,
    TagDetailView,
    TagListView,
    TagUpdateView
)


urlpatterns = [
    path("", TagListView.as_view(), name="list_tags"),
    path("<int:pk>/", TagDetailView.as_view(), name="show_tag"),
    path("create/", TagCreateView.as_view(), name="create_tag"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="delete_tag"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="edit_tag"),
]

brew_logs/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

from recipes.models import Recipe
USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class BrewLog(models.Model):
    name = models.CharField(max_length=120)
    author = models.ForeignKey(
        USER_MODEL,
        related_name="brew_logs",
        on_delete=models.CASCADE,
        null=True,
    )
    recipe = models.ForeignKey(
        Recipe,
        related_name="brew_logs",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    batch_size = models.FloatField()
    style = models.CharField(max_length=25, blank=True)
    bitterness = models.FloatField(validators=[MaxValueValidator(250), MinValueValidator(0)], blank=True, null=True)
    color = models.FloatField(blank=True, null=True)
    abv = models.FloatField(validators=[MaxValueValidator(25), MinValueValidator(0)], blank=True, null=True)
    brewing_date = models.DateField()
    date_updated = models.DateTimeField(auto_now=True)
    secondary_date = models.DateField(blank=True, null=True)
    bottling_date = models.DateField(blank=True, null=True)
    brewing_notes = models.TextField(blank=True, null=True)
    hop_notes = models.TextField(blank=True, null=True)
    yeast_notes = models.TextField(blank=True, null=True)
    fermentation_notes = models.TextField(blank=True, null=True)
    packaging_notes = models.TextField(blank=True, null=True)
    appearance = models.CharField(max_length = 500, blank=True, null=True)
    aroma = models.CharField(max_length = 500, blank=True, null=True)
    flavor = models.CharField(max_length = 500, blank=True, null=True)
    mouthfeel = models.CharField(max_length = 500, blank=True, null=True)

    def __str__(self):
        return f"{self.name}, {self.batch_size}g {self.style} on {self.brewing_date}" 

brew_logs/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from brew_logs.models import BrewLog


# Create your views here.
class BrewLogListView(LoginRequiredMixin, ListView):
    model = BrewLog
    template_name = "brew_logs/list.html"
    paginate_by = 20

    def get_queryset(self):
        return BrewLog.objects.filter(author=self.request.user)


class BrewLogDetailView(LoginRequiredMixin, DetailView):
    model = BrewLog
    template_name = "brew_logs/detail.html"


class BrewLogCreateView(LoginRequiredMixin, CreateView):
    model = BrewLog
    template_name = "brew_logs/create.html"
    fields = [
        "name", 
        "recipe", 
        "batch_size", 
        "style", 
        "bitterness", 
        "color", 
        "abv", 
        "brewing_date", 
        "secondary_date", 
        "bottling_date", 
        "brewing_notes",
        "hop_notes", 
        "yeast_notes", 
        "fermentation_notes", 
        "packaging_notes", 
        "appearance", 
        "flavor",
        "aroma", 
        "mouthfeel",
    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("show_brewlog", args=[self.object.id])


class BrewLogDeleteView(LoginRequiredMixin, DeleteView):
    model = BrewLog
    template_name = "brew_logs/delete.html"
    success_url = reverse_lazy("list_brewlogs")


class BrewLogUpdateView(LoginRequiredMixin, UpdateView):
    model = BrewLog
    template_name = "brew_logs/edit.html"
    fields = [
        "name", 
        "recipe", 
        "batch_size", 
        "style", 
        "bitterness", 
        "color", 
        "abv", 
        "secondary_date", 
        "bottling_date", 
        "brewing_notes", 
        "aroma", 
        "flavor",
        "hop_notes", 
        "yeast_notes", 
        "fermentation_notes", 
        "packaging_notes", 
        "appearance",
        "flavor",
        "aroma", 
        "mouthfeel"
    ]
    success_url = reverse_lazy("list_brewlogs")

brew_logs/templates/brew_logs/create.html
{% extends 'base.html' %}

{% block title %}
    New Brew Log |
{% endblock %}

{% block content %}
    <main class="container brew-log-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} 
            <div class="control">
                <button class="button">Create</button>
            </div>
        </form>
    </main>
{% endblock content %}

brew_logs/templates/brew_logs/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete {{ brewlog.name }} |
{% endblock %}

{% block content %}
    <main class="container">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ brewlog }}"?</p>
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete</button>
            </div>
        </form>
    </main>
{% endblock content %}

brew_logs/templates/brew_logs/detail.html
{% extends 'base.html' %}

{% load markdownify %}

{% block title %}
    {{ brewlog.name }} |
{% endblock title %}

{% block content %}
    <main class="container brew-log-detail">
        <div class="brew-log-options-bar">
            <a href="{% url 'edit_brewlog' brewlog.id %}">Edit</a>
            <a href="{% url 'delete_brewlog' brewlog.id %}">Delete</a>
        </div>        
        <h1>{{ brewlog.name }}</h1>
        <p>{{ brewlog.description|markdownify }}</p>
        <h2>Batch Details</h2>
            <table class="brew-log-stats">
                <thead>
                    <tr>
                        <th>Batch Size</th>
                        <th>Style</th>
                        <th>Bitterness</th>
                        <th>Color</th>
                        <th>ABV</th>
                        <th>Brewing Date</th>
                        <th>Date of Secondary</th>
                        <th>Date of Bottling/Kegging</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ brewlog.batch_size }} gallons</td>
                        <td>{{ brewlog.style|title }}</td>
                        <td>{{ brewlog.bitterness }} IBU</td>
                        <td>{{brewlog.color }}</td>
                        <td>{{ brewlog.abv }}%</td>
                        <td>{{ brewlog.brewing_date }}</td>
                        {% if brewlog.secondary_date %}
                            <td>{{brewlog.secondary_date }}</td>
                        {% else %}
                            <td> </td>
                        {% endif %}
                        {% if brewlog.bottling_date %} 
                            <td>{{ brewlog.bottling_date }}</td>
                        {% else %}
                            <td> </td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        <h2>Brewing Notes</h2>
            <table class="brew-log-notes">
                <thead>
                    <tr>
                        <th>Brewing Notes</th>
                        <th>Hop Notes</th>
                        <th>Yeast Notes</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% if brewlog.brewing_notes %}
                            <th>{{ brewlog.brewing_notes }}</th>
                        {% else %}
                            <th></th>
                        {% endif %}
                        {% if brewlog.hop_notes %}
                            <th>{{ brewlog.hop_notes }}</th>
                        {% else %}
                            <th></th>
                        {% endif %}
                        {% if brewlog.yeast_notes %}
                            <th>{{ brewlog.yeast_notes }}</th>
                        {% else %}
                            <th></th>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        <h2>Tasting Notes</h2>
            <table class="brew-log-taste-notes">
                <thead>
                    <tr>
                        <th>Appearance</th>
                        <th>Flavor</th>
                        <th>Aroma</th>
                        <th>Mouthfeel</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        {% if brewlog.appearance %}
                            <th>{{ brewlog.appearance }}</th>
                        {% else %}
                            <th></th>
                        {% endif %}
                        {% if brewlog.flavor %}
                            <th>{{ brewlog.flavor }}</th>
                        {% else %}
                            <th></th>
                        {% endif %}
                        {% if brewlog.aroma %}
                            <th>{{ brewlog.aroma }}</th>
                        {% else %}
                            <th></th>
                        {% endif %}
                        {% if brewlog.mouthfeel %}
                            <th>{{ brewlog.mouthfeel }}</th>
                        {% else %}
                            <th></th>
                        {% endif %}
            </table>
    </main>
{% endblock content %}

brew_logs/templates/brew_logs/edit.html
{% extends 'base.html' %}

{% block title %}
    Edit {{ brewlog.name }} |
{% endblock %}

{% block content %}
    <main class="container brew-log-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
            <button class="button">Update</button>
            </div>
        </form>
    </main>
{% endblock content %}

brew_logs/templates/brew_logs/list.html
{% extends 'paginate.html' %}

{% block title %}
    My Brew Logs |
{% endblock %}

{% block content %}
    <main class="container">
        <h1 class="brew-log-title">My Brew Logs</h1>
        <div class="brew-log-options-bar">
            <a href="{% url 'create_brewlog' %}">Create a new Brew Log</a>
        </div>
        {% if brewlog_list %}
            <div class="brew-log-grid">
                {% for brewlog in brewlog_list %}
                    <div class="brew-log-card">
                        <h2 class="brew-log-card-title">
                            <a href="{% url 'show_brewlog' brewlog.pk %}">{{ brewlog.name }}</a>
                        </h2>
                        <p class="brew-log-card-info">
                            {{ brewlog.batch_size }} gallons - {{ brewlog.style|title }}
                            on {{ brewlog.brewing_date }}
                        </p>
                    </div>
                {% endfor %}
            </div> 
        {% else %} 
            <p>You do not have any brew logs</p>
        {% endif %} 
    </main>
{% endblock content %} 