brewr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("accounts/", include("accounts.urls")),
    path("tags/", include("tags.urls")),
    path("brew_logs", include("brew_logs.urls")),
    path("", RedirectView.as_view(url="/recipes/"), name="home"),
]

recipes/urls.py
from django.urls import path

from recipes.views import (
    RecipeCreateView,
    RecipeDeleteView,
    RecipeDetailView,
    RecipeListView,
    RecipeUpdateView,
)


urlpatterns = [
    path("", RecipeListView.as_view(), name="list_recipes"),
    path("<int:pk>/", RecipeDetailView.as_view(), name="show_recipe"),
    path("create/", RecipeCreateView.as_view(), name="create_recipe"),
    path("<int:pk>/delete/", RecipeDeleteView.as_view(), name="delete_recipe"),
    path("<int:pk>/edit/", RecipeUpdateView.as_view(), name="edit_recipe"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagDeleteView,
    TagDetailView,
    TagListView,
    TagUpdateView
)


urlpatterns = [
    path("", TagListView.as_view(), name="list_tags"),
    path("<int:pk>/", TagDetailView.as_view(), name="show_tag"),
    path("create/", TagCreateView.as_view(), name="create_tag"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="delete_tag"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="edit_tag"),
]

recipes/models.py
from django.db import models
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
STYLE_CHOICES = (
    ("",""),
    ("lager","LAGER"),
    ("stout","STOUT"),
    ("sour","SOUR"),
)

FERMENTABLE_CHOICES = (
    ("",""),
    ("pilsner","Pilsner"),
    ("pale ale","Pale Ale"),
    ("white wheat","White Wheat"),
    ("caramel 60","Caramel / Crystal 60L"),
    ("chocolate","Chocolate"),
)

HOP_CHOCIES = (
    ("",""),
    ("cascade","Cascade"),
    ("citra","Citra"),
    ("mosaic","Mosaic"),
    ("simcoe","Simcoe"),
    ("fuggle","Fuggle"),
)

HOP_TYPES = (
    ("",""),
    ("pellet","Pellet"),
    ("whole cone","Whole Cone"),
)

class Recipe(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    image = models.URLField(null=True, blank=True)
    batch_size = models.FloatField(validators=[MinValueValidator(0)])
    style = models.CharField(max_length=5, choices=STYLE_CHOICES, default="")
    author = models.ForeignKey(
        USER_MODEL,
        related_name="recipes",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Fermentable(models.Model):
    name = models.CharField(max_length=11, choices=FERMENTABLE_CHOICES, default="")
    amount = models.FloatField(validators=[MinValueValidator(0)])
    gravity = models.FloatField(validators=[MinValueValidator(0)])
    color = models.FloatField(validators=[MaxValueValidator(600), MinValueValidator(0)])
    recipe = models.ForeignKey(
        "Recipe",
        related_name="fermentables",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return f"{self.amount}lbs - {self.name}"


class Hop(models.Model):
    variety = models.CharField(max_length=7, choices=HOP_CHOCIES, default="")
    amount = models.FloatField()
    hop_type = models.CharField(max_length=10, choices=HOP_TYPES, default="")
    alpha_acids = models.FloatField()
    time = models.TimeField(blank=True, null=True)
    recipe = models.ForeignKey(
        "Recipe",
        related_name="hops",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return f"{self.amount}oz. {self.variety}"

recipes/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from recipes.models import Recipe

# Create your views here.
class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipes/list.html"
    paginate_by = 20

    def get_queryset(self):
        return Recipe.objects.filter(author=self.request.user)


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipes/detail.html"


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = "recipes/create.html"
    fields = ["name", "description", "image", "batch_size", "style"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("show_recipe", args=[self.object.id])


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    template_name = "recipes/edit.html"
    fields = ["name", "description", "image", "batch_size", "style"]
    success_url = reverse_lazy("list_recipes")


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    template_name = "recipes/delete.html"
    success_url = reverse_lazy("list_recipes")

recipes/templates/recipes/create.html
{% extends 'base.html' %}

{% block title %}
    New Recipe |
{% endblock %}

{% block content %}
    <main class="container recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} 
            <div class="control">
                <button class="button">Create</button>
            </div>
        </form>
    </main>
{% endblock content %}

recipes/templates/recipes/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete {{ recipe.name }} |
{% endblock %}

{% block content %}
    <main class="container">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ recipe }}"?</p>
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete</button>
            </div>
        </form>
    </main>
{% endblock content %}

recipes/templates/recipes/detail.html
{% extends 'base.html' %}

{% load markdownify %}

{% block title %}
    {{ recipe.name }} |
{% endblock title %}

{% block content %}
    <main class="container recipe-detail">
        <div class="recipe-options-bar">
            <a href="{% url 'edit_recipe' recipe.id %}">Edit</a>
            <a href="{% url 'delete_recipe' recipe.id %}">Delete</a>
        </div>        
        {% if recipe.image %}
            <img src="{{ recipe.image }}" class="pull-right">
        {% endif %}
        <h1>{{ recipe.name }}</h1>
        <p>{{ recipe.description|markdownify }}</p>
        <h2>Recipe Details</h2>
            <table>
                <thead>
                    <tr>
                        <th>Batch Size</th>
                        <th>Style</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ recipe.batch_size }} gallons</td>
                        <td>{{ recipe.style|title }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <p>Tags: {% for tag in recipe.tags.all %}{{ tag.name }} {% endfor %}</p>
    </main>
{% endblock content %}

recipes/templates/recipes/edit.html
{% extends 'base.html' %}

{% block title %}
    Edit {{ recipe.name }} |
{% endblock %}

{% block content %}
    <main class="container recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
            <button class="button">Update</button>
            </div>
        </form>
    </main>
{% endblock content %}

recipes/templates/recipes/list.html
{% extends 'paginate.html' %}

{% block title %}
    My Recipes |
{% endblock %}

{% block content %}
    <main class="container">
        <h1 class="recipe-title">My Recipes</h1>
        <div class="recipe-options-bar">
            <a href="{% url 'create_recipe' %}">Create a new recipe</a>
        </div>
        {% if recipe_list %}
            <div class="recipe-grid">
                {% for recipe in recipe_list %}
                    <div class="recipe-card">
                        <h2 class="recipe-card-title">
                            <a href="{% url 'show_recipe' recipe.pk %}">{{ recipe.name }}</a>
                        </h2>
                        <p class="recipe-card-info">{{ recipe.batch_size }} gallons - {{ recipe.style|title }}</p>
                    </div>
                {% endfor %}
            </div> 
        {% else %} 
            <p>You do not have any recipes</p>
        {% endif %} 
    </main>
{% endblock content %} 