brewr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("accounts/", include("accounts.urls")),
    path("tags/", include("tags.urls")),
    path("brew_logs", include("brew_logs.urls")),
    path("", RedirectView.as_view(url="/recipes/"), name="home"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagCreateView,
    TagDeleteView,
    TagDetailView,
    TagListView,
    TagUpdateView
)


urlpatterns = [
    path("", TagListView.as_view(), name="list_tags"),
    path("<int:pk>/", TagDetailView.as_view(), name="show_tag"),
    path("create/", TagCreateView.as_view(), name="create_tag"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="delete_tag"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="edit_tag"),
]

tags/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=25)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")
    author = models.ForeignKey(
        USER_MODEL,
        related_name="tags",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

tags/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from tags.models import Tag

# Create your views here.
class TagListView(LoginRequiredMixin, ListView):
    model = Tag
    template_name = "tags/list.html"
    paginate_by = 20

    def get_queryset(self):
        return Tag.objects.filter(author=self.request.user)


class TagDetailView(LoginRequiredMixin, DetailView):
    model = Tag
    template_name = "tags/detail.html"


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tags/create.html"
    fields = ["name", "recipes"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("show_tag", args=[self.object.id])


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    template_name = "tags/edit.html"
    fields = ["name", "recipes"]
    success_url = reverse_lazy("list_tags")


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = "tags/delete.html"
    success_url = reverse_lazy("list_tags")

tags/templates/tags/create.html
{% extends 'base.html' %}

{% block title %}
    New Tag |
{% endblock %}

{% block content %}
    <main class="container tag-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} 
            <div class="control">
                <button class="button">Create</button>
            </div>
        </form>
    </main>
{% endblock content %}

tags/templates/tags/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete {{ tag.name }} |
{% endblock %}

{% block content %}
    <main class="container">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ tag }}"?</p>
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete</button>
            </div>
        </form>
    </main>
{% endblock content %}

tags/templates/tags/detail.html
{% extends 'base.html' %}

{% load markdownify %}

{% block title %}
    tag:"{{ tag.name }}" |
{% endblock title %}

{% block content %}
    <main class="container tag-detail">
        <div class="tag-options-bar">
            <a href="{% url 'edit_tag' tag.id %}">Edit</a>
            <a href="{% url 'delete_tag' tag.id %}">Delete</a>
        </div>
        <h2>Recipes with "{{ tag.name }}"</h2>
        {% for recipe in tag.recipes.all %}
            <p>
                <a href="{% url 'show_recipe' recipe.pk %}">{{ recipe.name }}</a>
            </p>
        {% endfor %}
    </main>
{% endblock content %}

tags/templates/tags/edit.html
{% extends 'base.html' %}

{% block title %}
    Edit {{ tag.name }} |
{% endblock %}

{% block content %}
    <main class="container tag-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
            <button class="button">Update</button>
            </div>
        </form>
    </main>
{% endblock content %}

tags/templates/tags/list.html
{% extends 'paginate.html' %}

{% block title %}
    Tags |
{% endblock %}

{% block content %}
    <main class="container">
        <h1 class="tag-title">Tags</h1>
        <div class="tag-options-bar">
            <a href="{% url 'create_tag' %}">Create a new tag</a>
        </div>
        <div class="tag-grid">
            {% for tag in tag_list %}
                <div class="recipe-card">
                    <h2 class="recipe-card-title">
                        <a href="{% url 'show_tag' tag.pk %}">{{ tag.name }}</a>
                    </h2>
                    {% for recipe in tag.recipes.all %}
                        <p>
                            <a href="{% url 'show_recipe' recipe.pk %}">{{ recipe.name }}</a>
                        </p>
                    {% endfor %}
                </div>
            {% empty %}
                <div>
                    <h1>No tags, yet</h1>
                    <p>
                    Would you like to
                    <a href="{% url 'create_tag' %}">create</a>
                    one?
                    </p>
                </div>
            {% endfor %}
        </div>
    </main>
{% endblock content %}